= Ubuntu-based Docker Image with AWS CLI & Amplify, and command line development tools
Martin Cribbins <mcribbins@stonefifteen.com>
:icons: image

== Purpose

Various types of engineering or design development requires a combination of GUI-based and command-line based tools; here
"GUI-based" refers to tools whose Graphical User Interface is *native* to the hosting OS, as opposed to being HTML
browser-based. In many cases an operational environment for the GUI-based tools must be established, within which the
use of command line tools (via a "Shell") is the most productive approach. As so many engineers are well accustomed to
using a Bash (or similar) shell under Linux, this Docker Image provides that shell environment such that it may be used
on most operating systems that can run a Docker Container.

This Image extends the basic Linux+Bash environment by providing tools that are used in many "full stack" development
scenarios, notably:
* Amazon Web Services (AWS) CLI tool
* AWS Amplify
* Git 2.23
*

=== Host OS configuration, image mount points

The image will always look to the mountpoint */local* for access to root of the host user's home directory. The */root* mount point is always used to access the root directory of the host machine.

* Windows 10
** Mount
* Linux
** nested list item
*** nested nested list item 1
*** nested nested list item 2
* macOS
** blah

This is a paragraph.

.Example block title
====
Content in an example block is subject to normal substitutions.
====

.Sidebar title
****
Sidebars contain aside text and are subject to normal substitutions.
****

==== Third level heading

[#id-for-listing-block]
.Listing block title
----
Content in a listing block is subject to verbatim substitutions.
Listing block content is commonly used to preserve code input.
----

===== Fourth level heading

.Table title
|===
|Column heading 1 |Column heading 2

|Column 1, row 1
|Column 2, row 1

|Column 1, row 2
|Column 2, row 2
|===

====== Fifth level heading

[quote,firstname lastname,movie title]
____
I am a block quote or a prose excerpt.
I am subject to normal substitutions.
____

[verse,firstname lastname,poem title and more]
____
I am a verse block.
  Indents and endlines are preserved in verse blocks.
____

== First level heading

TIP: There are five admonition labels: Tip, Note, Important, Caution and Warning.

// I am a comment and won't be rendered.

. ordered list item
.. nested ordered list item
. ordered list item

The text at the end of this sentence is cross referenced to <<_third_level_heading,the third level heading>>

== First level heading

This is a link to the https://docs.asciidoctor.org/home/[Asciidoctor documentation].
This is an attribute reference {url-quickref}[that links this text to the AsciiDoc Syntax Quick Reference].
