name: TestingCheckout

on:
  workflow_dispatch

permissions:
  contents: write
  pages: write
  id-token: write
  deployments: write

jobs:
  build:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
    steps:
      
        - name: co
            uses: actions/checkout@v4
            with:
            token: ${{ secrets.PAT_GENERAL}} # `GH_PAT` is a secret that contains your PAT
        
